name = "Stalburg Recreation Project"
author = "Avalon Servers"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "99c5eb5027223f859ef8495d0a132c27f493e96b3d9255e0e04d09766434090e"

[versions]
forge = "43.2.14"
minecraft = "1.19.2"
