name = "Stalburg Recreation Project"
author = "Avalon Servers"
version = "1.5.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ddacdeaa1c95d69cb5b2d534c1442823d2c7aa3b0562eb2ac47f37bec9f595bb"

[versions]
forge = "43.2.14"
minecraft = "1.19.2"
