name = "Stalburg Recreation Project"
author = "Avalon Servers"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8217d65179fb7006ae41b59878a72c772c1c32d700e314bf73d06f222b277a24"

[versions]
minecraft = "1.19.2"
quilt = "0.19.2"

[options]
acceptable-game-versions = ["1.19.2"]
