name = "Small Gauge Goodies for Immersive Railroading."
filename = "Small Gauge Goodies.zip"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/2677/970/Small%20Gauge%20Goodies.zip"
hash-format = "sha1"
hash = "deaa48efbe0269986898d94ab0f16156b7d5acec"

[update]
[update.curseforge]
file-id = 2677970
project-id = 298310
