name = "Ascent: Frozen Hell"
author = "Avalon Servers"
version = "0.0.5"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0e76b62c236de86c8a033940064f7b93de80ca32b7d21f9fb142b43b7a03ef31"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
