name = "Ascent: Frozen Hell"
author = "Avalon Servers"
version = "0.0.6"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "87e09a18fe4e3c9f5fdc9f27b55038332048e26e17d5a842865fa53a5689060a"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
