name = "Ascent: Frozen Hell"
author = "Avalon Servers"
version = "0.0.5"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "658d67371c7ba1af30b6885ab4d59b915b64bdd05beb377be9c71ae27957535e"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
