name = "Ascent: Frozen Hell"
author = "Avalon Servers"
version = "0.0.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4d1aec46292743f1bfa697a34844fa7a171907f524f9c95149b80c5c2d2ee8b3"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
