name = "Dragon Realm"
author = "Reika"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c589083adb255cde3950e8c17d6019f14d2cc3f1415bb55a0fac4ade6d4cd803"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
