name = "Ascent: Override"
author = "Alex Zero"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c4d80a2feca671da1d1bbc055f62a8626ef05139b7aeec554a9198ceec4e838b"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
