name = "Ascent: Override"
author = "Alex Zero"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2ecaae569be2692d9a5cd06a608be1e237b88b92f01fc38c857a57d845d243fa"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
