name = "Ascent: Override"
author = "Alex Zero"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9f98fec2d1b35d7a8f522081875acbb157edb3e3912384e3edb127ccbdcfbeb3"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
