name = "Uncontainable"
author = "CitadelCore"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "de35415627d2283615f18302bfec390a5729c5e2bb4c908399e1296585c82db7"

[versions]
forge = "10.13.0.1150"
minecraft = "1.7.10"
