name = "Uncontainable"
author = "CitadelCore"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "09ff008d5881954551053830650f78bba7b5e7db869d9d27a1acbeba23f0f707"

[versions]
forge = "10.13.0.1150"
minecraft = "1.7.10"
