name = "Uncontainable"
author = "CitadelCore"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cabbdd7cae845fbd9037864b7a4d2e1146e707c08b0cc768bfc9b32461c6de05"

[versions]
forge = "10.13.0.1150"
minecraft = "1.7.10"
