name = "Descent: Frozen Hell"
author = "Avalon Servers"
version = "1.9.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "605493680a8007a18edf854b4c7ec2b7c19300fb4e1b1799309d02fcbd45900f"

[versions]
forge = "14.23.0.2486"
minecraft = "1.12.2"
