name = "Descent: Frozen Hell"
author = "Avalon Servers"
version = "1.27.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "089f441ce679a3e4035a22a962a5aa456c58de46cc418949e1a65de3863f22b8"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
