name = "Descent: Frozen Hell"
author = "Avalon Servers"
version = "1.24.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6346eaec47df5149dea02ae28963756dfd07427896f8018e93627f845c7b3b41"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
