name = "Descent: Frozen Hell"
author = "Avalon Servers"
version = "1.19.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "72cafe760c02c08962c26083bc4d734ccb7e685550a72d23853f8c78536fbb7d"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
