name = "Descent: Frozen Hell"
author = "Avalon Servers"
version = "1.9.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a9017cb5a00a81440a79b51e6904a96d483bb2671b4a4b6b335ff01e03de2990"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
