name = "Descent: Frozen Hell"
author = "Avalon Servers"
version = "1.27.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4f95dc7a878436b2194d153aae47aca8556714e887b8f0089de54064996a1d0a"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
