name = "Descent: Frozen Hell"
author = "Avalon Servers"
version = "1.16.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "84714c3a8ef52b6f97eff2966adf325ae2ee931ff1e655bd3d2702f4060a10ce"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
