name = "Descent: Frozen Hell"
author = "Avalon Servers"
version = "1.15.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dd765e6815187ffdf9307a132f48f8cc76dc3b5b2f5d66c7522fc739810a010c"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
