name = "Descent: Frozen Hell"
author = "Avalon Servers"
version = "1.31.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6bafedf49767fa1f4778fa371e3efeab4bd0fd858e0ae32a1f8ea3cb09f080b9"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
