name = "Descent: Frozen Hell"
author = "Avalon Servers"
version = "1.18.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ca931cdd5fcd8a06371b1564f2803cfa7ef91cbc1a4ede8dc5af5711b14771dd"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
