name = "Descent: Frozen Hell"
author = "Avalon Servers"
version = "1.9.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ee5b8181fa178e43c1d7608a4cfa752e9d55450ac65bdf470845d2c86dd368cf"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
