name = "Descent: Frozen Hell"
author = "Avalon Servers"
version = "1.9.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5f60ed97be4b779bcd482e059ac6692fea4d4ce5f14ae80e862b1dc665e9aec4"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
