name = "Descent: Frozen Hell"
author = "Avalon Servers"
version = "1.21.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e1230329267898e08d2d133addba243fc5b58446385d7456ceeb5e7e42883fba"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
