name = "Descent: Frozen Hell"
author = "Avalon Servers"
version = "1.9.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "73072b783e0a10e2a913ad51fb7600092da567714e802adab1954225d3a06d91"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
