name = "Descent: Frozen Hell"
author = "Avalon Servers"
version = "1.17.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a42a5f6718df3716430c2a638c472fff47a75302c609caa2a05b440767fedc56"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
