name = "Descent: Frozen Hell"
author = "Avalon Servers"
version = "1.25.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "29dc2a4caf5f8587c5976912dd9cf3731ac5b9c2c47bb269a05df479024e6759"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
