name = "Descent: Frozen Hell"
author = "Avalon Servers"
version = "1.9.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7dd23bf2157ab109f2ab49ddc267a5dbf7a74b036ba6fb3dda650a782d1e13ee"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
