name = "Descent: Frozen Hell"
author = "Avalon Servers"
version = "1.16.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "56d6967fca9ccd3f0d55a7e4b2255f4e6d2539a1c9c29a6a81e7e5c964f66351"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
