name = "Descent: Frozen Hell"
author = "Avalon Servers"
version = "1.9.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "10eca07ccfde2cf005c2ae7677a8d01b6692dfe3123a7ec2877c8575167817bb"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
