name = "Descent: Frozen Hell"
author = "Avalon Servers"
version = "1.30.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ec999694265fef0ade42049d79bc4685d20f3b2e7aeca0dfa751470c91c3be52"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
