name = "Descent: Frozen Hell"
author = "Avalon Servers"
version = "1.9.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "49bce89b87d619169e1765560b1310af38fb643b8150d85185c2e52045bb641b"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
