name = "Descent: Frozen Hell"
author = "Avalon Servers"
version = "1.30.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "37f060d06066e990d92b0d93764c1a4bf16890ccc39db63a241303fbc1c819e9"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
