name = "Descent: Frozen Hell"
author = "Avalon Servers"
version = "1.19.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "61fe959e4ad0b9e982f22a8a211d5e2e1705eb1bcea5d97e2df9062216cb7cff"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
