name = "Descent: Frozen Hell"
author = "Avalon Servers"
version = "1.26.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "890aa50a5f87623542348c6b813f39c4ad9d645ba205e14f965f341e2f6186b0"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
