name = "Descent: Frozen Hell"
author = "Avalon Servers"
version = "1.9.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fe699a2ab7998ef5eeeac298165d985ca40552918da64e9f72a28b93be427577"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
