name = "Descent: Frozen Hell"
author = "Avalon Servers"
version = "1.9.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "557da622bc30c54792bde940273450b5e08a42a5901288a8b932c22b78f6f9b9"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
