name = "Descent: Frozen Hell"
author = "Avalon Servers"
version = "1.14.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aa6023ff41c2f92d96ebd1bddc6ba518e25094f64d4997f5542d5e2c2890bb35"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
