name = "Descent: Frozen Hell"
author = "Avalon Servers"
version = "1.19.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8e3d8b5fd5739be47909d2723d41eb13bdd28e16fb85e14926bc18bb2b41d471"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
