name = "Descent: Frozen Hell"
author = "Avalon Servers"
version = "1.9.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d3f1bdb43ec5758b9065089a221a3a7ec0e65a8e324c65a10a9ef79e8948183c"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
