name = "Descent: Frozen Hell"
author = "Avalon Servers"
version = "1.9.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "388144fdf6712d0040b047a837e19a6a4fdf0e7121483313545c56d3c693eb81"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
