name = "Dragon's Modern British"
filename = "Dragons_Modern_British1.3.zip"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3016/197/Dragons_Modern_British1.3.zip"
hash-format = "sha1"
hash = "12a890aec03f9cff67e7213fc2bf83ddb3b068bf"

[update]
[update.curseforge]
file-id = 3016197
project-id = 367886
