name = "Dragon's Modern British"
filename = "Dragons_Modern_British1.3.zip"
side = "both"

[download]
hash-format = "sha1"
hash = "7d25d71c7d988ecb2216a5c9f09f16b65e1bdd84"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 3550367
project-id = 367886
