name = "TFL Pack tom23 v100 fixed"
filename = "TFL_Pack_tom23_v100.zip"
side = "client"

[download]
url = "https://skyem.co.uk/files/TFL_Pack_tom23_v100_fixed_4.zip"
hash-format = "sha256"
hash = "2fae308fcbafd0820217d16f541fc34ff078b7b2df330a6f68165f674b898bce"
