name = "Matoi Vanilla Pack (IR)"
filename = "MVP-IR-1.7-by-FrozeRain.zip"
side = "both"

[download]
hash-format = "sha1"
hash = "2982bd9b8c82c48a6ad117c1306a5bc291dadddd"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 4023677
project-id = 349491
