name = "Matoi Vanilla Pack (IR)"
filename = "MVP-IR-1.6-by-FrozeRain.zip"
side = "both"

[download]
hash-format = "sha1"
hash = "ee8b516016b9d6b8b1708227dbc6de9fd8f1c798"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 3510281
project-id = 349491
