name: Deploy
on:
  release:
    types: [created]
  workflow_dispatch: {}

jobs:
  build:
    name: Build release artifacts
    runs-on: ubuntu-22.04
    steps:
      - name: Fetch repository
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Set up Go runtime
        uses: actions/setup-go@v2
        with:
          go-version: ^1.18.2
      - name: Set up Python runtime
        uses: actions/setup-python@v3
      - name: Install Python dependencies
        run: pip install -r requirements.txt
      - name: Install Packwiz
        run: go install github.com/packwiz/packwiz@latest
      - name: Build pack zip files
        run: ./scripts/ci-build-all.sh
      - name: Upload packs artifact
        uses: actions/upload-artifact@v2
        with:
          name: packs
          path: build
      - name: Upload data artifact
        uses: actions/upload-artifact@v2
        with:
          name: data
          path: packs
      - name: Upload tools artifact
        uses: actions/upload-artifact@v2
        with:
          name: tools
          path: tools
  deploy-web:
    name: Deploy CDN
    needs: ["build"]
    runs-on: ubuntu-22.04
    environment: production
    steps:
      - name: Download packs artifact
        uses: actions/download-artifact@v2
        with:
          name: packs
          path: artifacts/packs
      - name: Download data artifact
        uses: actions/download-artifact@v2
        with:
          name: data
          path: artifacts/data
      - name: Sync artifacts with bucket
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: parallax-assets
          AWS_S3_ENDPOINT: https://s3.eu-west-1.wasabisys.com
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-west-1
          SOURCE_DIR: artifacts
  deploy-mc:
    name: Deploy Minecraft server
    needs: ["build"]
    runs-on: ubuntu-22.04
    environment: production
    steps:
      - name: Download tools artifact
        uses: actions/download-artifact@v2
        with:
          name: tools
          path: artifacts/tools
      - name: Copy tools to server
        uses: appleboy/scp-action@v0.1.1
        with:
          host: srv1.avalonsrv.com
          key: ${{ secrets.AVALON_SERVER_SSH }}
          username: avalon-deploy
          source: artifacts/tools
          target: /var/lib/avalon/mc/tools
          strip_components: 2
          rm: true
      - name: Run pack installation and restart
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: srv1.avalonsrv.com
          key: ${{ secrets.AVALON_SERVER_SSH }}
          username: avalon-deploy
          script: |
            BASE_PATH=/var/lib/avalon/mc
            doas systemctl stop avalon-mc-ascent
            (cd "$BASE_PATH/ascent" && java -Xmx4G -jar $BASE_PATH/tools/packwiz-installer-bootstrap.jar -g -s server https://s3.eu-west-1.wasabisys.com/parallax-assets/data/ascent/frozenhell/pack.toml)
            ln -sf $BASE_PATH/ascent/forge-1.12.2-14.23.5.2860.jar "$BASE_PATH/ascent/server.jar"
            doas systemctl start avalon-mc-ascent
