name: Test
on: push

jobs:
  build:
    name: Validate packs
    runs-on: ubuntu-20.04
    steps:
      - name: Fetch repository
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Set up Go runtime
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16.13
      - name: Install Packwiz
        run: go install github.com/packwiz/packwiz@latest
      - name: Validate packs
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          scripts/ci-test-build.sh
