name: Update
on:
  schedule:
    - cron: "0 0,8,16 * * *"
  workflow_dispatch: {}

jobs:
  update:
    name: Scan for applicable mod updates
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Fetch repository
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Set up Go runtime
        uses: actions/setup-go@v2
        with:
          go-version: ^1.18.2
      - name: Set up Python runtime
        uses: actions/setup-python@v3
      - name: Install Python dependencies
        run: pip install -r requirements.txt
      - name: Install Packwiz
        run: go install github.com/packwiz/packwiz@latest
      - name: Run update script
        run: ./scripts/ci-update-all.sh
      - name: Commit and push
        run: |
          git config --global user.email "autoupdate@parallax.vertex-x.net"
          git config --global user.name "Parallax Autoupdate"
          git commit -m "Automated update commit"
          git push
