name = "Nullifaction"
author = "CitadelCore"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "046d2d0c484306eb1fdd41f173013f4e4686f644a8bd481a4bf1e2016d066de6"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
