name = "Uncontainable"
author = "CitadelCore"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a14d65e25fb0a1293c9e14ba4f1a2cd377f118bb5e44cef027054e97870ba662"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
